[pyprland]
plugins = [
  "scratchpads",
  "magnify",
  "expose",
  "shortcuts_menu",
  "toggle_special",
]

[scratchpads.term]
# CHANGED: Now uses Kitty with a specific class name
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
animation = "fromTop"
unfocus = "hide"
excludes = "*"
lazy = true
multi = false

[scratchpads.volume]
command = "pavucontrol"
animation = "fromLeft"
class = "org.pulseaudio.pavucontrol" # Use the real internal name
size = "40% 70%"
unfocus = "hide"
lazy = true
margin = 20 # 90 might be too far off-screen depending on resolution

[shortcuts_menu.entries]

"Color picker" = [
    {name="format", options=["hex", "rgb", "hsv", "hsl", "cmyk"]},
    "sleep 0.2; hyprpicker --format [format] -a" # sleep to let the menu close before the picker opens
]
